services:
  # MinIO для объектного хранилища
  minio:
    image: quay.io/minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"  # S3 API
      - "9001:9001"  # Web Console
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    networks:
      - trino-network

  # Автоматическое создание бакетов в MinIO
  createbuckets:
    image: quay.io/minio/mc:latest
    depends_on:
      - minio
    restart: on-failure
    entrypoint: >
      /bin/sh -c "
      sleep 5;
      /usr/bin/mc alias set localminio http://minio:9000 minioadmin minioadmin;
      /usr/bin/mc mb localminio/my-bucket;
      /usr/bin/mc mb localminio/trino-data;
      exit 0;
      "
    networks:
      - trino-network

  # PostgreSQL для Hive Metastore
  metastore-db:
    image: postgres:13
    container_name: metastore-db
    environment:
      POSTGRES_DB: metastore
      POSTGRES_USER: hive
      POSTGRES_PASSWORD: hivepassword
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - trino-network

  init-metastore:
    image: apache/hive:3.1.3
    container_name: init-metastore
    depends_on:
      - metastore-db
    volumes:
      - ./metastore/metastore-site.xml:/opt/hive/conf/metastore-site.xml
      - ./postgresql-driver.jar:/opt/hive/lib/postgresql.jar
      - ./custom-entrypoint.sh:/custom-entrypoint.sh
    entrypoint: ["/bin/sh", "/custom-entrypoint.sh"]  # ← ПОЛНОСТЬЮ СВОЙ ENTRYPOINT
    networks:
      - trino-network
    # restart: on-failure
    


  # Hive Metastore сервис
  metastore:
    image: apache/hive:3.1.3
    container_name: metastore
    depends_on:
      - init-metastore
      - metastore-db
    environment:
      SERVICE_NAME: metastore
      DB_DRIVER: postgresql
      DB_URL: jdbc:postgresql://metastore-db:5432/metastore
      DB_USER: hive
      DB_PASSWORD: hivepassword
    volumes:
      - ./metastore/metastore-site.xml:/opt/hive/conf/metastore-site.xml
      - ./metastore/core-site.xml:/opt/hadoop/conf/core-site.xml
      - ./postgresql-driver.jar:/opt/hive/lib/postgresql.jar  # ← ДОБАВЬТЕ ДРАЙВЕР      
    command: /opt/hive/bin/start-metastore -p 9083
    networks:
      - trino-network

  # Trino coordinator
  trino:
    image: trinodb/trino:latest
    container_name: trino
    depends_on:
      - metastore
      - minio
    ports:
      - "8080:8080"  # Trino UI
    volumes:
      - ./conf/hive.properties:/etc/trino/catalog/hive.properties
      - ./conf/postgres.properties:/etc/trino/catalog/postgres.properties
    networks:
      - trino-network

volumes:
  minio_data:
  postgres_data:

networks:
  trino-network:
    driver: bridge
