services:
  # PostgreSQL для Hive Metastore
  postgres:
    image: postgres:13
    container_name: postgr
    hostname: postgres
    environment:
      POSTGRES_DB: metastore_db
      POSTGRES_USER: hive
      POSTGRES_PASSWORD: hivepassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - hive-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U hive -d metastore_db"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Hadoop Namenode
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    hostname: namenode
    environment:
      - CLUSTER_NAME=hadoop-cluster
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
    volumes:
      - namenode_data:/hadoop/dfs/name
    ports:
      - "9870:9870"  # Namenode Web UI
      - "9000:9000"  # HDFS
    networks:
      - hive-network
    env_file:
      - ./hadoop.env

  # Hadoop Datanode
  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode
    hostname: datanode
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
    volumes:
      - datanode_data:/hadoop/dfs/data
    ports:
      - "9864:9864"  # Datanode Web UI
    networks:
      - hive-network
    depends_on:
      - namenode
    env_file:
      - ./hadoop.env

  hive-metastore:
    image: apache/hive:4.0.0
    container_name: hive
    environment:
      - SKIP_SCHEMA_INIT=true  # Критически важно!
    ports:
      - "9083:9083"
    volumes:
      - ./postgresql-42.5.1.jar:/opt/hive/lib/postgresql.jar
      - ./hive-metastore-entrypoint.sh:/entrypoint.sh
    entrypoint: ["/bin/sh", "/entrypoint.sh"]  # Полная замена entrypoint
    networks:
      - hive-network
    depends_on:
      - postgres
      - namenode

  # Trino (замена HiveServer2)
  trino:
    image: trinodb/trino:latest
    container_name: trino
    hostname: trino
    ports:
      - "8080:8080"  # Trino Web UI
    volumes:
      - ./trino-config:/etc/trino
      - ./trino-data:/var/trino/data
      - ./trino-entrypoint.sh:/entrypoint.sh
      - warehouse_data:/opt/hive/data/warehouse
    entrypoint: ["/bin/bash", "/entrypoint.sh"]      
    networks:
      - hive-network
    depends_on:
      - hive-metastore
      - namenode

volumes:
  postgres_data:
    driver: local
  namenode_data:
    driver: local
  datanode_data:
    driver: local
  warehouse_data:
    driver: local

networks:
  hive-network:
    driver: bridge
