# Iceberg connector configuration
# connector.name=iceberg
# iceberg.catalog.type=hive_metastore

# # CORRECT warehouse location property for Iceberg
# # iceberg.warehouse=s3a://warehouse/

# # Hive metastore configuration
# hive.metastore.uri=thrift://metastore:9083

# # S3 configuration
# fs.native-s3.enabled=true
# s3.aws-access-key=
# s3.aws-secret-key=
# s3.region=eu-central-1
# s3.endpoint=http://s3.eu-central-1.amazonaws.com
# s3.path-style-access=true

# s3.canned-acl=PUBLIC_READ_WRITE

# s3.access-key-id=your-access-key
# s3.secret-access-key=your-secret-key

connector.name=iceberg
iceberg.catalog.type=jdbc
iceberg.jdbc-catalog.driver-class=org.postgresql.Driver
iceberg.jdbc-catalog.connection-url=jdbc:postgresql://metastore-db:5432/metastore
iceberg.jdbc-catalog.connection-user=hiveuser
iceberg.jdbc-catalog.connection-password=hivepassword
iceberg.jdbc-catalog.default-warehouse-dir=s3://tiny

# TODO: figure out where this is used
iceberg.jdbc-catalog.catalog-name=catalog-todo

# object store
# https://trino.io/docs/current/object-storage.html
fs.hadoop.enabled=false
fs.native-s3.enabled=true
s3.endpoint=http://minio-service:9000
s3.region=us-east-1
s3.aws-access-key=muser
s3.aws-secret-key=mpassword
s3.path-style-access=true